### ISSUE TITLE
definition of truncating_mutations is missing

### ISSUE THREAD

**Issue by jyu2012** [taylor-lab/annotateMaf#1]
Hi There,

I tried to call hotspot_annotate_maf and got the error message below:
Error in Variant_Classification %in% truncating_mutations : 
  object 'truncating_mutations' not found

Checked your source package and I didn't find anywhere truncating_mutation was defined. Just wonder if it's possible to fix.

thanks,

**Comment by kpjonsson** [comment]
Should be fixed by 48e6eaa37b527a39fc4533f1defc01df3362ca31.
