### ISSUE TITLE
`brca_annotate_maf` error with newest installation

### ISSUE THREAD

**Issue by anoronh4** [taylor-lab/annotateMaf#5]
We are finding the following error with our latest docker build including `taylor-lab/annotateMaf`. The error is:
```
Error: Problem with `mutate()` column `annot`.
i `annot = purrr::pmap(...)`.
x Problem with `filter()` input `..2`.
i Input `..2` is `start - 1`.
x Input `..2` must be a logical vector, not a double.
Backtrace:
     x
  1. +-annotateMaf::brca_annotate_maf(maf)
  2. | +-`%>%`(...)
  3. | +-dplyr::mutate(...)
  4. | \-dplyr:::mutate.data.frame(...)
  5. |   \-dplyr:::mutate_cols(.data, ..., caller_env = caller_env())
  6. |     +-base::withCallingHandlers(...)
  7. |     \-mask$eval_all_mutate(quo)
  8. +-dplyr::select(., -annot)
  9. +-dplyr::mutate(...)
 10. +-purrr::pmap(...)
 11. | \-annotateMaf:::.f(...)
 12. |   +-`%>%`(...)
 13. |   +-dplyr::filter(...)
 14. |   \-dplyr:::filter.data.frame(...)
 15. |     \-dplyr:::filter_rows(.data, ..., caller_env = caller_env())
 16. |       +-base::withCallingHandlers(...)
 17. |       \-mask$eval_all_filter(dots, env_filter)
 18. +-purrr::transpose(.)
 19. +-dplyr:::abort_glue(...)
 20. | +-rlang::exec(abort, message = message, class = class, !(!(!data)))
 21. | \-(function (message = NULL, class = NULL, ..., trace = NULL, parent = NULL, ...
 22. |   \-rlang:::signal_abort(cnd)
 23. |     \-base::signalCondition(cnd)
 24. \-(function (e) ...
Execution halted
```
We haven't changed much about the R packages in Dockerfile but some of the dependencies are not version-controlled. I noticed that plyr == 1.8.4 and dplyr == 0.8.3 in the last working image, and the newest image has plyr == 1.8.6 and dplyr == 1.0.7. When I added a line at the end of the dockerfile to revert plyr and dplyr back to 1.8.4 and 0.8.3, the `brca_annotate_maf` function completed without error.

I am not sure if reverting both packages was necessary or if just one would have been sufficient. Although I was able to design a workaround, perhaps users of the package would benefit from an update that is compatible with recent versions of plyr/dplyr.

**Comment by gongyixiao** [comment]
Different version of dplyr behaves different as newer version of dplyr only allow logical vectors, not single values anymore, which gives actual error. Previously version not giving the error is because the `start -1` was considered as a logical value same as `1` or `true`, making the filter doesn't do anything at all.
